#pragma kernel DrawAgentMap

struct Agent {
	float2 position;
	float angle;
	int4 speciesMask;
	int speciesIndex;
};

RWStructuredBuffer<Agent> agents;
uint numAgents;

RWTexture2D<float4> TargetTexture;

[numthreads(16,1,1)]
void DrawAgentMap (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numAgents) {
		return;
	}

	Agent agent = agents[id.x];
	// Draw to texture in 2D space
	int2 coord = int2(agent.position);
	TargetTexture[coord] = 1;
} 