#pragma kernel DrawAgentMap

struct Agent {
	float3 position;
	float angle;
	float4 mask;
	int speciesIndex;
	
};

RWStructuredBuffer<Agent> agents;
uint numAgents;

RWTexture3D<float4> TargetTexture;

[numthreads(16,1,1)]
void DrawAgentMap (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numAgents) {
		return;
	}


	Agent agent = agents[id.x];
	// Draw to trail map in 3D space
	int3 coord = int3(agent.position);
	TargetTexture[coord] = 1;
}